# Generated by Django 3.2.8 on 2021-10-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211012_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='element',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Element',
        ),
    ]
