# Generated by Django 3.2.8 on 2021-10-13 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211012_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='data',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='form', to='api.data'),
        ),
    ]
