# Generated by Django 3.2.8 on 2021-10-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_form_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
    ]
